### ISSUE TITLE
LineageOS 18.1 系统的手机无法连接的问题

### ISSUE THREAD

**Issue by Felix-Bao** [mingzhixian/Easycontrol#15]
受控手机为三星Note3，系统为LineageOS 18.1，Android版本为11。无线调试已打开，在PC端使用scrcpy-win64-v2.1.1连接正常流畅，没有问题。
主控手机为小米12s Ultra，在其上安装"易控"，输入受控手机的IP和端口后连接无反应，长时间后提示“连接server失败”。但没有“连接ADB失败”的提示，说明端口和IP没有问题，且如果我设置了自定义的分辨率，受控手机的屏幕分辨率会更改。
同样情况下，另一台受控手机为三星S7，Android版本为8.0，我用小米手机控制它就没有任何问题。
早些时候，当那台三星Note3的系统是Android 9.0的时候，我也曾连接成功过。现在升级到Android 11就不行了，跟系统版本有关系吗？

**Comment by Felix-Bao** [comment]
我之前安装的是最新的V1.0.3-dev，更换为旧的V12.8.1旧可以连接了，很奇怪阿，是小米的MiUI问题吗？

**Comment by mingzhixian** [comment]
好的，我会检查安卓11的适配问题

**Comment by mingzhixian** [comment]
请检查新版本是否还存在该问题

**Comment by Felix-Bao** [comment]
刚刚试用了一下，很不错，没有什么兼容性问题。能否增加声音开关，比如我不想听到被控手机上应用的声音。

**Comment by mingzhixian** [comment]
最新版本已支持关闭音频传输
