### ISSUE TITLE
最新版1.0.9 “被控端熄屏”无法关闭

### ISSUE THREAD

**Issue by Felix-Bao** [mingzhixian/Easycontrol#17]
如题，无论是否打开这个选项，被控端总是熄屏，即时断开连接也无法恢复。

**Comment by mingzhixian** [comment]
只要处于远程控制中，会一直检测被控端状态，保持被控端处于唤醒状态，被控端熄屏开关是用来设置是否关闭被控端屏幕的背光。断开连接后会恢复背光状态，并自动锁屏。

**Comment by Felix-Bao** [comment]
好的，那如何实现老版本中的主控被控同时显示呢？至少在我关闭易控后让被控手机恢复亮屏。

**Comment by mingzhixian** [comment]
正常来说，关闭被控端熄屏功能，就会主被控同时亮屏显示了，至于断开连接后保持被控端亮屏，这个下一个版本会添加功能开关

**Comment by mingzhixian** [comment]
请使用新版本，并关闭自动屏幕控制功能

**Comment by Felix-Bao** [comment]
按照你说的还是不行，我暂时的解决方式是在被控手机上安装MacroDroid，配合自定义的宏命令让被控手机在断开连接后几秒钟自动亮屏。

鸣之弦 ***@***.***> 于 2023年11月2日周四 20:20写道：
