### ISSUE TITLE
增加有线连接

### ISSUE THREAD

**Issue by Layne2016** [mingzhixian/Easycontrol#18]
你好，我想把旧手机投屏到车机上，能不能增加有线的连接以降低延迟和提高画质。

**Comment by Layne2016** [comment]
我看到代码有有线连接相关的，不知道为何有线连接会失败

**Comment by mingzhixian** [comment]
是的，代码已经写了有线连接，但是目前处于不可用状态，因为不知为何从usb读取数据始终返回错误，

**Comment by mingzhixian** [comment]
所以在更新日志中并没有提及有线连接的支持

**Comment by Layne2016** [comment]
好的，谢谢
