### ISSUE TITLE
0.4版本以上到正式版，一旦连接到被控端就黑屏，然后控制不了被控端

### ISSUE THREAD

**Issue by qpdbzzz** [mingzhixian/Easycontrol#19]
0.4测试版还能行0.4以上就不行了

**Comment by qpdbzzz** [comment]
黑屏是闪烁的 黑棒天然后就突然游一下画面，然后继续黑
然后活动屏幕被扌空端无反应

**Comment by mingzhixian** [comment]
连接上后被控端黑屏是正常现象，易控的设定是，连接上后以及远程控制中，自动唤醒并保持被控端唤醒状态，易控设置里面的“被控端熄屏开关”是用来设置是否关闭被控端屏幕的背光，断开连接后会恢复背光状态，并自动锁屏。

**Comment by qpdbzzz** [comment]
> 连接上后被控端黑屏是正常现象，易控的设定是，连接上后以及远程控制中，自动唤醒并保持被控端唤醒状态，易控设置里面的“被控端熄屏开关”是用来设置是否关闭被控端屏幕的背光，断开连接后会恢复背光状态，并自动锁屏。

关键这个被控息屏我不管开关都是黑屏，然后而且是闪烁黑屏一直都是黑的然后有时候闪一下画面 我后盲操的话也是控制不了被控手机的
1.0.4就真常，往上所有版本都是黑闪

**Comment by mingzhixian** [comment]
嗯，1.0.4是因为没有实现这个功能，后续添加了这个功能。
如果方便的话，请使用电脑连接被控端，使用adb shell命令进入被控端终端，输入“dumpsys deviceidle | grep mScreenOn”命令，查看输出结果，分别做两次，一次是被控端亮屏时执行上述命令的结果，一次是被控端熄屏时执行上述命令的结果。
易控是使用上述命令判断被控端屏幕状态从而执行亮屏或熄屏动作的，如果你的手机执行上述命令存在问题可能就会导致错乱。

**Comment by qpdbzzz** [comment]
我这个指令好像是不管熄屏还是亮屏都是true
mScreenOn=true

**Comment by mingzhixian** [comment]
好的，这就是问题了

**Comment by mingzhixian** [comment]
请使用新版本，并关闭自动屏幕控制功能

**Comment by qpdbzzz** [comment]
https://github.com/mingzhixian/Easycontrol/assets/145204697/42c8d4d3-faba-4efa-bae3-54f04495684b

https://github.com/mingzhixian/Easycontrol/assets/145204697/c7b6cca9-b7a0-4c82-b1bf-a3394b668169

**Comment by qpdbzzz** [comment]
确定了，还是不行
https://github.com/mingzhixian/Easycontrol/assets/145204697/e0a9a4a2-2c7d-4b30-b69f-2b1e401401bf

https://github.com/mingzhixian/Easycontrol/assets/145204697/5230b65e-aac9-40da-9631-6cb2ed50ac23

https://github.com/mingzhixian/Easycontrol/assets/145204697/df4ca770-7e55-4615-8265-8c0ccc259f25
 https://github.com/mingzhixian/Easycontrol/assets/145204697/6f844725-d5d6-45fb-922b-a3363974ccf6

**Comment by mingzhixian** [comment]
关闭自动控制和息屏控制后，就不会对屏幕做任何控制了
还有请不要一直不停的点灯泡按键，那个是电源键，不停的点就是不停的按电源键
如果是小米设备请打开usb安全模式才可以触控



打开自动屏幕控制：连接自动唤醒，连接中保持唤醒，断开自动锁定

关闭自动屏幕控制：完全用工具栏灯泡按钮操控电源键，本来是熄屏，那连接上也是熄屏，需要手动唤醒，本来是唤醒状态，断开后也会是唤醒状态，所以想关闭，就在断开前手动锁定

打开息屏控制：唤醒后关闭内置屏幕的背光

**Comment by qpdbzzz** [comment]
点灯泡，我那个只是想给你看一下 强制黑屏，点亮灯泡后又自动黑屏了，可能我手的频率有点快，当时真的是自动黑屏的

我电灯泡只在黑屏的情况下轻点一下

然后后半段是我手动按实体电源键，也是按一下之后亮一下屏，然后就自动黑屏了

我那个息屏  自动 什么的也确全关了，但是可能不生效，还是咋的（最开头）

**Comment by qpdbzzz** [comment]
作者你能看一下那个熄屏相关的
点击关闭后是否全部已经关了
程序
我怀疑是不是哪里没关干净啊
因为目前就是老是强制黑屏
设置项关闭无用

**Comment by mingzhixian** [comment]
软件本身实现是没问题的，这是实现的效果
https://drive.saymzx.top/s/A9WSz

**Comment by qpdbzzz** [comment]
> 软件本身实现是没问题的，这是实现的效果
> https://drive.saymzx.top/s/A9WSz

你这个是连接后自动熄一下屏，还是本身手机就是熄屏的？
我也是这样设置的，然后被控手机是亮屏的，一旦连接就自动黑屏了 点击亮屏之后还强制黑屏
如果实在用不了，只能用0.4版本了

**Comment by mingzhixian** [comment]
首先，系统分为锁定和唤醒两种状态，至于被控端屏幕亮不亮那是背光的事

打开自动屏幕控制：连接自动唤醒，连接中保持唤醒，断开自动锁定

关闭自动屏幕控制：完全用工具栏灯泡按钮操控电源，本来是锁定，那连接上也是锁定，需要手动唤醒，本来是唤醒状态，断开后也会是唤醒状态

打开息屏控制：一般来说，系统锁定后会自动关闭背光，唤醒后会自动开启背光，打开熄屏控制后会在唤醒后仍然关闭内置屏幕的背光

**Comment by qpdbzzz** [comment]
https://github.com/mingzhixian/Easycontrol/assets/145204697/cbca5fa5-1b3b-4f5f-be39-d818b013a4d8

**Comment by mingzhixian** [comment]
进入被控端，将/data/local/tmp目录下的文件清空，另外将易控卸载重新安装最新版本

**Comment by cuicsi** [comment]
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月3日(周五) 下午2:21
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [mingzhixian/Easycontrol] 0.4版本以上到正式版，一旦连接到被控端就黑屏，然后控制不了被控端 (Issue #19)




 
https://github.com/mingzhixian/Easycontrol/assets/145204697/cbca5fa5-1b3b-4f5f-be39-d818b013a4d8

**Comment by qpdbzzz** [comment]
> 进入被控端，将/data/local/tmp目录下的文件清空，另外将易控卸载重新安装最新版本

被控端安装最新易控无用该黑屏还是黑屏，用不了还是用不了

**Comment by mingzhixian** [comment]
被控端：将/data/local/tmp目录下的文件清空
主控端：将易控卸载重新安装最新版本

**Comment by qpdbzzz** [comment]
> 被控端：将/data/local/tmp目录下的文件清空
> 主控端：将易控卸载重新安装最新版本

不得行，不得行 我还是用04吧，谢谢了

**Comment by qpdbzzz** [comment]
对了突然记起一件事，以前用甲壳虫的时候，那里也有一个息屏 之后也是黑屏用不了，不过那个点击关掉了，能正常用 不过你这个开不开都用不了了新版本12刚也试了（也就是说，我那被控端的手机必须得屏幕亮着，物理上亮着，才能控制）反正我老觉得你那个设置熄屏控制关闭，不生效 还是有一些开着的，一直在命令黑屏检测到亮了就立刻又黑了

**Comment by mingzhixian** [comment]
熄屏控制的作用是关闭背光。

打开自动屏幕控制后，会在连接时检测一次，检测到为锁定状态则唤醒，并根据熄屏控制设定判断是否关闭被控端屏幕背光；之后控制过程中会定期重复上述检测，断开时则是反过来，将设备锁定。

我说了。你要是觉得不兼容就关闭自动屏幕控制，手动控制设备状态，连接上是黑屏就手动点击灯泡按钮唤醒，想被控端也开着背光就把熄屏控制关掉。

**Comment by qpdbzzz** [comment]
演示视频你也有看到了，我是设置全部都关掉的，他还是给我黑

**Comment by mingzhixian** [comment]
唔，那就没办法了，代码目前看是没问题的，关掉自动控制后不会执行屏幕相关的代码，其他人也没反馈相似问题，所以暂时没头绪。

**Comment by mingzhixian** [comment]
或者你有兴趣的话，可以搞个内网穿透什么的，让我能够调试你的手机。。。
