### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by Wonder1031** [mingzhixian/Easycontrol#22]
老哥写的一直是我想找的软件，激动得打开使用发现报地址格式错误无法使用，尝试了局域网地址和公网域名均无效，还请指正
（无法上传图片，图片内容是toast提示java.lang.Exception:地址格式错误）

**Comment by mingzhixian** [comment]
格式在添加页面有说明，地址:端口号，举例
192.168.1.111:5555
[204e:212f::1]:5555
phone.ex.com:5555

**Comment by Wonder1031** [comment]
> 格式在添加页面有说明，地址:端口号，举例 192.168.1.111:5555 [204e:212f::1]:5555 phone.ex.com:5555

![EE451D953733157B92C771BABD7A28B7](https://github.com/mingzhixian/Easycontrol/assets/51465444/23820153-cf24-4b15-934f-e66a5def9716)
感谢回复，不过在多次尝试之后依然无果

**Comment by mingzhixian** [comment]
你是不是把地址输错位置了，第一行是名称，第二行是地址，
![Screenshot_20231110_173649](https://github.com/mingzhixian/Easycontrol/assets/72658846/ba1d07c3-6d67-40e4-8504-03b1435e3a8a)
