### ISSUE TITLE
华为novations 9手机，断开usb就无法连接

### ISSUE THREAD

**Issue by xuzhiyong017** [mingzhixian/Easycontrol#25]
设备：华为nova 9手机
系统：鸿蒙
问题：连接usb后 adb tcpip 5555 , 主控机可以连接上nova9 ，拔掉线就链接不上了

**Comment by EmotionalRonan** [comment]
@xuzhiyong017 
 华为手机 断开USB 链接 就掉线 可以参考这个试试

设置 - 系统和更新 -【开发人员选项】
拔掉数据线后，需要再次打开【开发人员选项】中的USB调试
打开【连接USB时总是弹出提示】，选择可传输文件
打开【开发者选项】中的“仅充电”模式下允许ADB调试

https://liuyong.blog.csdn.net/article/details/125917059
