### ISSUE TITLE
【提个建议】 能不能实现 两台 同WiFi 下的Android 手机 直接配对呢？

### ISSUE THREAD

**Issue by EmotionalRonan** [mingzhixian/Easycontrol#29]
每次 都要 链接到电脑 adb tcpip  这样比较麻烦。

Android 11 以上设备。可以通过配对码 无线匹配。
命令是：
```
adb pair [ipaddr:pair-port]   [pairing code]
adb connect [ipaddr:connect-port]
```

1. 🍔参考  甲壳虫adb 助手，可以直接通过配对码 无线链接 两台手机
![甲壳虫配对图片](https://images.cnblogs.com/cnblogs_com/emotionalronan/2372751/o_240116065350_Image_20240116145258.png)

2. 🎉或者 可不可以通过Shizuku 调用，直接实现无线匹配。
 https://github.com/RikkaApps/Shizuku

@mingzhixian 
看看能不能实现呢。。
😁🙏🏽🙏🏽🙏🏽

**Comment by mingzhixian** [comment]
新版本会支持有线连接，和通过有线连接打开无线调试，至于配对那个，挺麻烦不想搞

**Comment by faxmbo** [comment]
配对码挺麻烦的，建议个方法，我是直接弄了开机自动执行的一个脚本，在开机时设置端口并启动无线adb。就是不需要动受控端了，控制端直接无线连接就行
