### ISSUE TITLE
Android studio编译失败

### ISSUE THREAD

**Issue by SeaEastXu** [mingzhixian/Easycontrol#34]
![image](https://github.com/mingzhixian/Easycontrol/assets/14850488/b08712b3-cac3-4fcb-bc0a-3a08834fdd54)

**Comment by mingzhixian** [comment]
sdk和gradle不用关心，配置文件中都有的，报错是因为没有编译server文件，项目分两个模块，一个是主控端运行的app，一个是被控端运行的sever，首先要编译server模块，并把编译后的文件放入app模块内的raw文件夹，随后再编译app模块，运行时由app推送server至被控端。
编译server模块并移动至app内raw文件夹的步骤我写成了一个任务，执行server模块下的gradle任务：copyrelease 即可

**Comment by SeaEastXu** [comment]
感谢
