### ISSUE TITLE
自己打包的话，少了很多代码

### ISSUE THREAD

**Issue by q120379739** [mingzhixian/Easycontrol#36]
![image](https://github.com/mingzhixian/Easycontrol/assets/54164039/48fe0928-ad52-4abf-a3cf-c4184a77f065)

**Comment by toohandsome** [comment]
这是自己环境的问题， 核心只要注释掉首页的弹窗就行，其他不缺什么

**Comment by mingzhixian** [comment]
那是viewbinding，你构建一次即可，会自动生成的
