### ISSUE TITLE
希望 被控端 能主动打开 无线连接，并且可以自定义端口号

### ISSUE THREAD

**Issue by toohandsome** [mingzhixian/Easycontrol#37]
目前 需要在 主控、被控 用有线连接后，然后在主控端 开启被控端的无线连接；

这样操作挺麻烦的

**Comment by mingzhixian** [comment]
如果被控端能自己打开，我早就实现了

**Comment by mingzhixian** [comment]
这个涉及安全和隐私问题，没法软件自己打开的，安卓11以上的话可以通过开发者选项里的无线调试（易控不支持这种）取巧，但是操作起来也挺麻烦的，还不如插线打开，所以最新版本的教学视频，我只演示了一个打开方法，因为这个最容易理解，操作也最简化（唯一的缺点是可能没有转接头来连接手机）
