### ISSUE TITLE
联系不上

### ISSUE THREAD

**Issue by igsood** [mingzhixian/Easycontrol#38]
微信和QQ群都加不了

**Comment by mingzhixian** [comment]
微信群分享只有7天有效，小龙的垃圾设计，我没及时更新二维码，qq的二维码应该是有效的，
![qrcode_1713505006266](https://github.com/mingzhixian/Easycontrol/assets/72658846/83561496-fe2f-4c18-b8df-9a7ab0cd14ee)

仍然不行可加我qq：1963402801
